### ISSUE TITLE
selectionIndicator does not show

### ISSUE THREAD

**Issue by silverh00d** [hightower/HTHorizontalSelectionList#16]
Hi,

If I do the following: `[self.selectionList setSelectedButtonIndex:1 animated:NO]`, the selectedButton is correct, but the selectionIndicator does not show until I select another button. Any ideas?

Thanks in advance!

**Comment by ios-apps** [comment]
Add [self.selectionList reloadData]; before [self.selectionList setSelectedButtonIndex:1 animated:NO];

**Comment by silverh00d** [comment]
Great! Thanks!
