### ISSUE TITLE
Button alignment

### ISSUE THREAD

**Issue by malcommac** [hightower/HTHorizontalSelectionList#17]
Could be an interesting feature a property called .alignment where you can specify the default button alignment (now they are aligned from left)

**Comment by erikackermann** [comment]
@malcommac great idea.  Would you want center, left, right as options?

**Comment by malcommac** [comment]
Yes it could be a great addition.
Moreover you should allow to set title's font.

**Comment by erikackermann** [comment]
@malcommac as of the last release, you can now specify font: https://github.com/hightower/HTHorizontalSelectionList/blob/master/HTHorizontalSelectionList/HTHorizontalSelectionList.h#L33

Regarding the horizontal alignment: this only applies if there aren't enough items in the selection list to fill the width of the control, correct?  The current method (left aligned) populates the list from the left.  We could conceivably do this from the right, but what would it mean to have a center aligned selection list?

I guess there could be special logic for aligning the buttons if they don't fill the width of the list...

**Comment by malcommac** [comment]
Ops forget it, I've just see the new property .font right now :)
Yes alignment is valid only if content < bounds of the controls itself, otherwise it does not make sense (or not?)
