### ISSUE TITLE
Tests: Unit Test

### ISSUE THREAD

**Issue by erikackermann** [hightower/HTHorizontalSelectionList#18]
Things I'd like if you're adding tests for this project:

Tooling: Kiwi

Areas to look at:
- Edge cases with 0/n+1 errors and the number of items specified by the data source
- Tests verifying that reloadData is working correctly

**Comment by qzytcl** [comment]
How to add a array with tableView ？And ,maping element to titleButton?

**Comment by erikackermann** [comment]
I'm sorry, I'm not sure I understand the question @qzytcl
