### ISSUE TITLE
How to load different views in the tab?

### ISSUE THREAD

**Issue by gclsoft** [hightower/HTHorizontalSelectionList#25]
Such as a UITableViewController and a UIViewController, when I click the second tab, it switch from the UITableViewController to UIViewController, instead of just changing the UILabel text in the same view.
How to load different views in the tab?

**Comment by erikackermann** [comment]
@gclsoft you probably want to use the methods `[UIViewController addChildViewController:]` and `[UIViewController transitionFromViewController:toViewController:duration:options:animations:completion:]`.

You will need to setup your view hierarchy with a container View Controller that contains the HTHorizontalSelectionList and the first child view controller (use `addChildViewController` in viewDidLoad of this container VC).  And then in the HTHorizontalSelectionList delegate method `- selectionList:didSelectButtonWithIndex:`, you will tell the container to transition the current child VC off screen and add the next child.

See this for more information about child/parent view controllers: https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CreatingCustomContainerViewControllers/CreatingCustomContainerViewControllers.html
