### ISSUE TITLE
Border Color

### ISSUE THREAD

**Issue by itjunkii** [hightower/HTHorizontalSelectionList#40]
Hey!

Thanks for this awesome library, I noticed an issue that I am having trouble solving. If I tap a button I get a nice red border, if I scroll to make that button off screen and come back my border is gone, but it is still my highlighted selected color, any idea what I might be doing wrong?

Also, the newest update have made my list two rows for some reason.

Appreciate the help.

![screen shot 2015-06-11 at 1 37 39 pm](https://cloud.githubusercontent.com/assets/1059150/8115162/134d9a38-103f-11e5-90fa-ac1b72afa7ee.png)
![screen shot 2015-06-11 at 1 37 23 pm](https://cloud.githubusercontent.com/assets/1059150/8115164/13524d94-103f-11e5-9067-c7edaaab718a.png)
![screen shot 2015-06-11 at 1 37 33 pm](https://cloud.githubusercontent.com/assets/1059150/8115163/13521400-103f-11e5-818f-5b6178ef8fad.png)

**Comment by erikackermann** [comment]
@itjunkii sorry you are having issues.  I can reproduce your first issue (the selection border disappearing); that's a bug and I will fix it shortly.

Can you show me how you are setting up the selection list?  I'm not sure why you're getting the buttons to wrap onto a new line.

**Comment by erikackermann** [comment]
@itjunkii your first issue is fixed here: https://github.com/hightower/HTHorizontalSelectionList/pull/41

**Comment by erikackermann** [comment]
Going to close this issue.  Feel free to open another for the buttons wrapping onto multiple lines.

Also, feel free to email me a code snippet showing how you're setting this up (if you're more comfortable sharing it that way).
