### ISSUE TITLE
MultiRow issue

### ISSUE THREAD

**Issue by itjunkii** [hightower/HTHorizontalSelectionList#43]
Hi! Thanks for your help on the other issue.

Here is how I initialize my list. Interestingly if I revert to 0.5.1 I have no issues with the multiline rows

```
self.textSelectionList = [[HTHorizontalSelectionList alloc]
                              initWithFrame:CGRectMake(0,40, self.view.frame.size.width, 60)];
    self.textSelectionList.delegate = self;
    self.textSelectionList.dataSource = self;
    [self.textSelectionList setTitleFont:[UIFont fontWithName:@"HelveticaNeue" size:15.0]
                                forState:UIControlStateNormal];
    self.textSelectionList.selectionIndicatorColor = [UIColor redColor];
    self.textSelectionList.backgroundColor = [UIColor clearColor];
    [self.textSelectionList setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    [self.textSelectionList setTitleColor:[UIColor redColor] forState:UIControlStateSelected];
    self.textSelectionList.bottomTrimHidden = YES;
    self.textSelectionList.selectionIndicatorStyle = HTHorizontalSelectionIndicatorStyleButtonBorder;
    [self.view insertSubview:self.textSelectionList aboveSubview:blurMenu];
    self.textSelectionList.alpha = 0;
```

**Comment by erikackermann** [comment]
Awesome.  Thanks for sending me this @itjunkii 

I am able to reproduce the issue and I'll let you know if I find a fix.

**Comment by erikackermann** [comment]
@itjunkii so under the hood, this selection list is using a UICollectionView with a UICollectionViewFlowLayout.  If you make the selection list tall enough to show two (or more) rows of buttons, it will flow onto the next row.

I can fix this by using a custom layout, or maybe some easier way.

In the meantime, you can probably fix this by setting the buttonInsets to something larger enough that each button will be greater than half the height of your selection list.

`self.selectionList.buttonInsets = UIEdgeInsetsMake(10, 0, 10, 0);`

or what ever top/bottom insets work for you as long as `insets.top + insets.bottom + buttonHeight > selectionList.frame.size.height / 2` (and `buttonHeight` here is determined by the font you are using).

**Comment by erikackermann** [comment]
Checkout the latest version (0.5.5).  I think this should fix your issue.

**Comment by itjunkii** [comment]
Awesome!!! Thanks Erik, I'll give it a try at work tomorrow and let you know how it goes.

**Comment by itjunkii** [comment]
Works like a charm, thanks Erik!!!
