### ISSUE TITLE
setSelectedButtonIndex  bug 

### ISSUE THREAD

**Issue by liujianying** [hightower/HTHorizontalSelectionList#47]
If HTHorizontalSelectionListDataSource data when there are 30, the first item is selected by default. If you are using - (void) setSelectedButtonIndex: (NSInteger) selectedButtonIndex animated: (BOOL) animated jump 29 when the method does not automatically move to 29

**Comment by phoenixin** [comment]
I met the same problem. If the button is not shown on the screen, using - (void) setSelectedButtonIndex: (NSInteger) selectedButtonIndex animated: (BOOL) animated will not move to the button.

**Comment by erikackermann** [comment]
@liujianying thanks for creating this issue.  What version are you using, and do you know if this was working previously?

**Comment by liujianying** [comment]
Thank you very much, your date with under the new code. Now you know

**Comment by erikackermann** [comment]
This is fixed and will be included in next release (0.5.7)
