### ISSUE TITLE
Crash when setting selectedButtonIndex to -1

### ISSUE THREAD

**Issue by jiongge** [hightower/HTHorizontalSelectionList#51]
i add "self.textSelectionList reloadData];[self.textSelectionList setSelectedButtonIndex:-1];" in the example code at the end of "(void)viewDidLoad" and have a crash in "UICollectionViewLayoutAttributes *selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];"

so i add "if(_selectedButtonIndex < 0){
        selectedIndexPath = [NSIndexPath indexPathForItem:0 inSection:0];
    }" before "UICollectionViewLayoutAttributes *selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];",it seems all right.

**Comment by erikackermann** [comment]
@jiongge I'm not sure I follow.  Are you saying that you get a crash when you try to set `selectedButtonIndex` to -1?

```objc
[self.textSelectionList setSelectedButtonIndex:-1];
```

**Comment by erikackermann** [comment]
Yeah, I see a crash where you said if I try to set `selectedButtonIndex` to -1.  I think your fix will work.  Can you send a pull request?

**Comment by erikackermann** [comment]
@jiongge after giving this more thought, I don't know if there is a simple way to handle consumers of this API setting the selectedButtonIndex to something out of bounds.  How would you like that to be handled?  (setting the selected index to -1 say).

I am going to close this issue and leave it up to consumers of the API to check that the selectedButtonIndex isn't manually being set to something invalid.
