### ISSUE TITLE
Initial Selection - Align Issue

### ISSUE THREAD

**Issue by yagiz** [hightower/HTHorizontalSelectionList#55]
Hey,

I'm trying to select an item just after the init:

    [self.selectionList setCenterAlignButtons:YES];
    [self.selectionList setCenterOnSelection:YES];
    [self.selectionList setAutocorrectCentralItemSelection:YES];
    [self.selectionList setAutoselectCentralItem:YES];

After these I try to select an item:

    [self.selectionList setSelectedButtonIndex:self.selectedIndex animated:NO];

I can see that indicator centers to item and item changes color. But selected item is not centered. Could you fix this issue?

**Comment by akhatmullin** [comment]
For me that is interested too.

**Comment by erikackermann** [comment]
@yagiz it sounds like the issue is just with the behavior when programmatically setting the `selectedButtonIndex` when `centerOnSelection` is YES?  The programatically-selected button does not animate to the center?

**Comment by yagiz** [comment]
@erikackermann Yes. That's the issue.
