### ISSUE TITLE
Layout buttons to fit width of selection list

### ISSUE THREAD

**Issue by guyisra** [hightower/HTHorizontalSelectionList#61]
Is it possible to make the buttons of the selectionList to be spread out the entire width of the view?

Since when there are a few items it doesn't look that good when it is aligned (any alignment). But if chosen to be fill the size of the view, it will look "fuller"

I can send a PR, but I haven't figured out where the width of the buttons is set

**Comment by erikackermann** [comment]
@guyisra the closest thing the selection list supports currently would be setting `centerAlignButtons` to YES.  This will center the buttons if the total width of all buttons is less than the width of the selection list; it will not, however, resize the buttons to fill the screen as I think you are asking.
