### ISSUE TITLE
Darkening navigation bar color

### ISSUE THREAD

**Issue by nicklasta** [hightower/HTHorizontalSelectionList#63]
While implementing HTHorizontalSelectionList, it darkened the color of the navigation bar, is there a way to disable it?

Thanks

**Comment by erikackermann** [comment]
I'm not sure how this control could affect your navigation bar.  Can you post some code snippet?  Are you putting the HTHorizontalSelectionList in a subview of the nav bar?

**Comment by nicklasta** [comment]
Not sure how, but it looks like it also affects the color of my tab bar too,

-(void)setupHotizontalSelection {
    
    self.edgesForExtendedLayout = UIRectEdgeNone;
    
    self.textSelectionList = [[HTHorizontalSelectionList alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 40)];
    self.textSelectionList.delegate = self;
    self.textSelectionList.dataSource = self;
    
    self.textSelectionList.selectionIndicatorAnimationMode = HTHorizontalSelectionIndicatorAnimationModeLightBounce;
    self.textSelectionList.showsEdgeFadeEffect = YES;
    
    self.textSelectionList.selectionIndicatorColor = [UIColor colorWithRed:0.94 green:0.00 blue:0.33 alpha:1.0];
    
    [self.textSelectionList setTitleColor:[UIColor grayColor] forState:UIControlStateHighlighted];
    [self.textSelectionList setTitleFont:[UIFont systemFontOfSize:13] forState:UIControlStateNormal];
    [self.textSelectionList setTitleFont:[UIFont boldSystemFontOfSize:13] forState:UIControlStateSelected];
    [self.textSelectionList setTitleFont:[UIFont boldSystemFontOfSize:13] forState:UIControlStateHighlighted];
    
    self.ordertype = @[@"Ship Today",
                       @"Ship Tomorrow",
                       @"Processing",
                       @"Shipped",
                       @"Canceled",
                       ];
    
    [self.view addSubview:self.textSelectionList];
    
    self.textSelectionList.snapToCenter = YES;
}

**Comment by erikackermann** [comment]
I'm not sure without seeing more of how your view hierarchy is setup.  I assume the above code is in your view controller, and this view controller is presented inside of a navigation stack?

Can you show me how you are setting up your navigation controller?

I'm not sure how the selection list could be changing the navigation controller's appearance.
