### ISSUE TITLE
Background Colour Of Horizontal Selection List replaces the colour set in story board can we add images.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [hightower/HTHorizontalSelectionList#64]
I created a view in storyboard with my desired colour. But the horizontal selection list doesn't retain its colour set in story board but is replacing the colour. If we want our preferred colour, our only option is to set it manually. Can we add images?

**Comment by erikackermann** [comment]
@GABHISEKBUNTY I'm not sure what you mean by "can we add images?".  You can add background images to each button (each item in the selection list).

Setting the background color in your interface or storyboard file is currently not working; it will be overwritten as you are noticing.  I'm not sure if there is a simple way to extend the initWithCoder implementation, but feel free to submit a PR if you have any ideas.  Maybe this line:

```objc
    self.backgroundColor = [UIColor whiteColor];
``` 

in -commonInit could be conditional and only set background if it is unset?

**Comment by erikackermann** [comment]
Going to close this issue; HTHorizontalSelectionList does not fully support styling in storyboards.  If you have an idea on how this could be improved for storyboard support, please send a PR :)
