### ISSUE TITLE
Deselect with -1 causes crash in layoutAttributesForItemAtIndexPath

### ISSUE THREAD

**Issue by lexar** [hightower/HTHorizontalSelectionList#66]
I am trying to deselect a HTHorizontalSelectionList by setting the selectedButtonIndex to -1. This causes a crash in setSelectedButtonIndex:animated: HTHorizontalSelectionList.m at this point:

UICollectionViewLayoutAttributes *selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];

Because _selectedButtonIndex is -1, selectedIndexPath has -I think- NSNotFound as row:
Printing description of selectedIndexPath:
<NSIndexPath: 0x178562d0> {length = 2, path = 0 - 4294967295}

Consequently, layoutAttributesForItemAtIndexPath crashes:
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4294967295 beyond bounds [0 .. 43]'

Oddly, the example CatsViewController does the same and is not crashing. So I am half wondering why mine is, and half why the CatsViewController doesn't.
What am I missing? Do I have to ensure a certain layout exists before deselecting?

**Comment by erikackermann** [comment]
Yeah, I would guess this issue is caused because you are setting the selected button index to -1 before the selection list has been drawn.  Can you show more code or tell me how you are setting up the view hierarchy?

**Comment by lexar** [comment]
Hi, thanks!
The setup is a bit embedded with multiple other views.
Basically, I have a view class where I setup the list
self.selectionList = [[HTHorizontalSelectionList alloc] initWithFrame:CGRectMake(0, 0, self.containerView.frame.size.width, self.containerView.frame.size.height)];
    self.selectionList.selectionIndicatorStyle = HTHorizontalSelectionIndicatorStyleButtonBorder;
    self.selectionList.delegate = self;
    self.selectionList.dataSource = self;
    [self.containerView addSubview:self.selectionList];

I do regularly updates to resize frames:
CGRect parentFrame = self.superview.bounds;
    self.frame = parentFrame;
    self.containerView.frame = parentFrame;
    
    CGRect selectionFrame = self.selectionList.frame;
    selectionFrame.size.width = parentFrame.size.width;
    self.selectionList.frame = selectionFrame;

[self.selectionList reloadData];

The list is populated by an array, it works fine.
The problem happens much later, when I deselect the list after tapping an UIButton. 
The crash happens immediately on 
self.selectionList.selectedButtonIndex = -1;

I checked if the datasource is called, unfortunately it's not - it's not a nonexisting array index or similar. The index is -1. The array hasn't changed anyway. The error message is
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4294967295 beyond bounds [0 .. 43]'

Does that help?
I'm not sure what you mean with "before the selection list has been drawn". Should I do a reloadData before?

**Comment by lexar** [comment]
Hi,

I fixed this for me by changing setSelectedIndex:animated in HTHorizontalSelectionList.m from

    UICollectionViewLayoutAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];

to

    UICollectionViewLayoutAttributes *selectedCellAttributes;
    if (_selectedButtonIndex == -1) {
        selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:oldSelectedIndexPath];
    }
    else {
        selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];
    }

This works for me: It puts the list into a deselected state. As I am not sure if that is the desired intention of that method, I post it here as a suggestion.
