### ISSUE TITLE
 CenterAlignButtons bug ？？？

### ISSUE THREAD

**Issue by liujianying** [hightower/HTHorizontalSelectionList#68]
<img width="1203" alt="1e26acde-e37f-4a29-aac4-75874931d081" src="https://cloud.githubusercontent.com/assets/6265414/14306774/ce8bdc2a-fbfc-11e5-8e0a-1cb9742bffd4.png">
<img width="1094" alt="54c17b98-b8b7-403e-993c-15e22e1c79cc" src="https://cloud.githubusercontent.com/assets/6265414/14306775/cf65d966-fbfc-11e5-889d-47dd0fc084c3.png">

**Comment by erikackermann** [comment]
I'm not sure what you mean

**Comment by elicox** [comment]
I don't know what he mean neither, but in my case  if I only have two buttons, and the width is all the screen, I want the two buttons center, not on the left.

So Instead of this:
| B1 --  B2  ---------------------- |

This one:
| -------- B1 -------  B2 -------- |

**Comment by liujianying** [comment]
Two labels, input can appear different length of label content is not centered
self.carmakes = @[@"已领取AAA", @"待领取(0)"]   no problem
self.carmakes = @[@"已领取(0)", @"待领取(0)"]      ？？？？

**Comment by erikackermann** [comment]
I'm not entirely sure I understand your issue.  I'm guessing that you want your buttons to look like the first image?

When I set `centerAlignButtons` to YES (and only supply two "car makes"), I'm seeing it work like the first screenshot.  Is the only difference between your first and second example the button text?

**Comment by erikackermann** [comment]
I am able to repro what you are seeing with your different strings.  Let me see if I can figure out why this isn't working as expected.

**Comment by liujianying** [comment]
self.carmakes = @[@"已领取AAA", @"待领取(0)"];
self.carmakes = @[@"已领取(0)", @"待领取(0)"];
The same configuration as the first array can be used normally, but it's not additional
You can modify the contents of the above carMakes in your demo, and testing.

**Comment by erikackermann** [comment]
This should be fixed on master.  Take a look at this: https://github.com/hightower/HTHorizontalSelectionList/pull/71.

Will release a new version soon.
