### ISSUE TITLE
setSelectedButtonIndex crashing when being called from another instance

### ISSUE THREAD

**Issue by rauls4** [hightower/HTHorizontalSelectionList#73]
So I have to instances:
| menu1 item 1 | menu1 item 2 | menu1 item 3 | menu1 item 4 |
| menu2 item 1 | menu2 item 2 | menu2 item 3 | menu2 item 4 |

When the user selects any item on menu1, menu2 needs to select item 1

I am issuing a  setSelectedButtonIndex and the app crashes

Here is the code for the method that invokes it:

```objc
- (void)selectionList:(HTHorizontalSelectionList *)selectionList didSelectButtonWithIndex:(NSInteger)index {
     if (selectionList.tag == 1) {
          //_filter2view is an instance of HTHorizontalSelectionList with a tag of 0
          [_filter2view setSelectedButtonIndex:0];
     }
}
```

Unfortunately the crash is not very informative, It produces not console output, it just highlights a line in HTHorizontalSelectionList.m with a Thread 1: EXC_ARITHMETIC (code=EXC_i385_DIV, subcode=0x0) error.

This is the line:

` UICollectionViewLayoutAttributes *selectedCellAttributes = [self.collectionView.collectionViewLayout layoutAttributesForItemAtIndexPath:selectedIndexPath];`

**Comment by rauls4** [comment]
Solved. It was an implementation error, the second instance was inside a redundant object.

**Comment by kutakmir** [comment]
hey, what do you mean? I have the same issue
