### ISSUE TITLE
It would be more appropriate if tap area is covered entire tab content.

### ISSUE THREAD

**Issue by mixdesign** [hightower/HTHorizontalSelectionList#74]
It would be more appropriate if tap area is covered entire tab content. Now tap is handled only on label tap. There should be no padding (no empty untappable area) between tabs.

**Comment by Ravi-Mehta-ACE** [comment]
Good

**Comment by erikackermann** [comment]
Take a look at the latest version (0.7.1); this should resolve your issue.  For selection lists with title labels (if you implement `-selectionList:titleForItemWithIndex:`), the height of each button is now the full height of the collection view.
