### ISSUE TITLE
reload not working

### ISSUE THREAD

**Issue by JrPro1** [hightower/HTHorizontalSelectionList#83]
i am downloading data Asynchronous and calling reload of  HTHorizontalSelectionList and its not working! can any body help?

**Comment by erikackermann** [comment]
@JrPro1 can you provide some code examples of how you are using the library?

**Comment by erikackermann** [comment]
@JrPro1 is this still an issue for you?

**Comment by erikackermann** [comment]
Going to close this out.  Not enough information.
